# Generated by Django 2.2 on 2022-05-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(default='Denny Dep', max_length=40)),
                ('level', models.CharField(default='junior', max_length=10)),
                ('sub_size', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='.Net Developer', max_length=40)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='Temp_subj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Devops', max_length=40)),
                ('subject', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_subjects', to='api.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='.Net Developer', max_length=40)),
                ('grade', models.CharField(default='junior', max_length=40)),
                ('description', models.TextField()),
                ('feedback', models.CharField(default='He is also good', max_length=40)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.Interview')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
